//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Resources
{
    using System;


    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu()
        {
        }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Main.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string aboutToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Item ähnelt.
        /// </summary>
        internal static string addToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("addToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string closeToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("closeToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string editToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("editToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string exitToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("exitToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string fileToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("fileToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string helpToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("helpToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KR_neu
        {
            get
            {
                object obj = ResourceManager.GetObject("KR_neu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have added item! ähnelt.
        /// </summary>
        internal static string msgAdd
        {
            get
            {
                return ResourceManager.GetString("msgAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add item! ähnelt.
        /// </summary>
        internal static string msgAddError
        {
            get
            {
                return ResourceManager.GetString("msgAddError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die have been closing! ähnelt.
        /// </summary>
        internal static string msgClose
        {
            get
            {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to close file! ähnelt.
        /// </summary>
        internal static string msgCloseError
        {
            get
            {
                return ResourceManager.GetString("msgCloseError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to access Help file! ähnelt.
        /// </summary>
        internal static string msgHelpError
        {
            get
            {
                return ResourceManager.GetString("msgHelpError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die have been creating! ähnelt.
        /// </summary>
        internal static string msgNew
        {
            get
            {
                return ResourceManager.GetString("msgNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to create file! ähnelt.
        /// </summary>
        internal static string msgNewError
        {
            get
            {
                return ResourceManager.GetString("msgNewError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die have been opening! ähnelt.
        /// </summary>
        internal static string msgOpen
        {
            get
            {
                return ResourceManager.GetString("msgOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to open file! ähnelt.
        /// </summary>
        internal static string msgOpenError
        {
            get
            {
                return ResourceManager.GetString("msgOpenError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die have been printing! ähnelt.
        /// </summary>
        internal static string msgPrint
        {
            get
            {
                return ResourceManager.GetString("msgPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to print file! ähnelt.
        /// </summary>
        internal static string msgPrintError
        {
            get
            {
                return ResourceManager.GetString("msgPrintError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have removed item! ähnelt.
        /// </summary>
        internal static string msgRemove
        {
            get
            {
                return ResourceManager.GetString("msgRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to remove item! ähnelt.
        /// </summary>
        internal static string msgRemoveError
        {
            get
            {
                return ResourceManager.GetString("msgRemoveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have been saving ähnelt.
        /// </summary>
        internal static string msgSave
        {
            get
            {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have been saving as ähnelt.
        /// </summary>
        internal static string msgSaveAs
        {
            get
            {
                return ResourceManager.GetString("msgSaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save file! ähnelt.
        /// </summary>
        internal static string msgSaveAsError
        {
            get
            {
                return ResourceManager.GetString("msgSaveAsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save file! ähnelt.
        /// </summary>
        internal static string msgSaveError
        {
            get
            {
                return ResourceManager.GetString("msgSaveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to edit settings! ähnelt.
        /// </summary>
        internal static string msgSettingsError
        {
            get
            {
                return ResourceManager.GetString("msgSettingsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string newToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("newToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string openToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("openToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string printToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("printToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Item ähnelt.
        /// </summary>
        internal static string removeToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("removeToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save As ähnelt.
        /// </summary>
        internal static string saveAsToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("saveAsToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string saveToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("saveToolStripMenuItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string settingsToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("settingsToolStripMenuItem", resourceCulture);
            }
        }
    }
}
